version: "3.4"
services:
  redis:
    image: "redis:latest"
    networks:
      - molinfo_internal
  molinfo:
    build: .
    ports:
      - "8042:8042"
    environment:
      - MOLINFO_REDIS_HOST=redis
    networks:
      - molinfo_internal
      - internal
    volumes:
      - ./build/install/molinfo:/app:ro
networks:
  molinfo_internal:
  proxy_internal:
    external: true
