#!/usr/bin/env bash

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# We only validate the code if we push to main
		#
		if [[ $local_ref = "refs/heads/main" ]] ; then
			./gradlew check -q

			if [ $? -ne 0 ]
			then
				echo >&2 "Checks failed, I refuse to push to main"
				exit 1
			fi
		fi
	fi
done

exit 0